name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }}
          POSTGRES_USER: ${{ secrets.PGUSER }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Install Ruby and dependencies
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Gems
        run: bundle install

      # Set up database
      - name: Set up database schema
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:test:prepare

      # Run tests
      - name: Run tests
        run: bundle exec rspec spec/

      # Upload code coverage report
      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage/
